using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using Android;
using Android.Runtime;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyMetadata("BUILD_COMMIT", "2059f2bbde9a3f07dd3e2df24b21e63c14d3a7be")]
[assembly: AssemblyMetadata("BUILD_NUMBER", "20230915.2")]
[assembly: AssemblyMetadata("BUILD_TIMESTAMP", "9/15/2023 8:19:27 AM")]
[assembly: LinkerSafe]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: NamespaceMapping(Java = "android.support.v4.app", Managed = "Android.Support.V4.App")]
[assembly: NamespaceMapping(Java = "android.support.v4.graphics.drawable", Managed = "Android.Support.V4.Graphics.Drawable")]
[assembly: NamespaceMapping(Java = "android.support.v4.os", Managed = "Android.Support.V4.OS")]
[assembly: NamespaceMapping(Java = "androidx.core.accessibilityservice", Managed = "AndroidX.Core.AccessibilityService")]
[assembly: NamespaceMapping(Java = "androidx.core.app", Managed = "AndroidX.Core.App")]
[assembly: NamespaceMapping(Java = "androidx.core.app.unusedapprestrictions", Managed = "AndroidX.Core.App.UnusedAppRestrictions")]
[assembly: NamespaceMapping(Java = "androidx.core.content", Managed = "AndroidX.Core.Content")]
[assembly: NamespaceMapping(Java = "androidx.core.content.pm", Managed = "AndroidX.Core.Content.PM")]
[assembly: NamespaceMapping(Java = "androidx.core.content.res", Managed = "AndroidX.Core.Content.Resources")]
[assembly: NamespaceMapping(Java = "androidx.core.database", Managed = "AndroidX.Core.Database")]
[assembly: NamespaceMapping(Java = "androidx.core.database.sqlite", Managed = "AndroidX.Core.Database.SqlLite")]
[assembly: NamespaceMapping(Java = "androidx.core.graphics", Managed = "AndroidX.Core.Graphics")]
[assembly: NamespaceMapping(Java = "androidx.core.graphics.drawable", Managed = "AndroidX.Core.Graphics.Drawable")]
[assembly: NamespaceMapping(Java = "androidx.core.hardware.display", Managed = "AndroidX.Core.Hardware.Display")]
[assembly: NamespaceMapping(Java = "androidx.core.hardware.fingerprint", Managed = "AndroidX.Core.Hardware.Fingerprint")]
[assembly: NamespaceMapping(Java = "androidx.core.internal.view", Managed = "AndroidX.Core.Internal.View")]
[assembly: NamespaceMapping(Java = "androidx.core.location", Managed = "AndroidX.Core.Location")]
[assembly: NamespaceMapping(Java = "androidx.core.math", Managed = "AndroidX.Core.Math")]
[assembly: NamespaceMapping(Java = "androidx.core.net", Managed = "AndroidX.Core.Net")]
[assembly: NamespaceMapping(Java = "androidx.core.os", Managed = "AndroidX.Core.OS")]
[assembly: NamespaceMapping(Java = "androidx.core.provider", Managed = "AndroidX.Core.Provider")]
[assembly: NamespaceMapping(Java = "androidx.core.service.quicksettings", Managed = "AndroidX.Core.Service.QuickSettings")]
[assembly: NamespaceMapping(Java = "androidx.core.telephony", Managed = "AndroidX.Core.Telephony")]
[assembly: NamespaceMapping(Java = "androidx.core.telephony.mbms", Managed = "AndroidX.Core.Telephony.Mbms")]
[assembly: NamespaceMapping(Java = "androidx.core.text", Managed = "AndroidX.Core.Text")]
[assembly: NamespaceMapping(Java = "androidx.core.text.method", Managed = "AndroidX.Core.Text.Method")]
[assembly: NamespaceMapping(Java = "androidx.core.text.util", Managed = "AndroidX.Core.Text.Util")]
[assembly: NamespaceMapping(Java = "androidx.core.util", Managed = "AndroidX.Core.Util")]
[assembly: NamespaceMapping(Java = "androidx.core.view", Managed = "AndroidX.Core.View")]
[assembly: NamespaceMapping(Java = "androidx.core.view.accessibility", Managed = "AndroidX.Core.View.Accessibility")]
[assembly: NamespaceMapping(Java = "androidx.core.view.animation", Managed = "AndroidX.Core.View.Animation")]
[assembly: NamespaceMapping(Java = "androidx.core.view.autofill", Managed = "AndroidX.Core.View.AutoFill")]
[assembly: NamespaceMapping(Java = "androidx.core.view.contentcapture", Managed = "AndroidX.Core.View.ContentCapture")]
[assembly: NamespaceMapping(Java = "androidx.core.view.inputmethod", Managed = "AndroidX.Core.View.InputMethod")]
[assembly: NamespaceMapping(Java = "androidx.core.widget", Managed = "AndroidX.Core.Widget")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription(".NET for Android (formerly Xamarin.Android) bindings for AndroidX library 'androidx.core:core'.")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("Xamarin.AndroidX.Core")]
[assembly: AssemblyTitle("Xamarin.AndroidX.Core")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/xamarin/AndroidX.git")]
[module: RefSafetyRules(11)]
