using System;
using System.Text;

namespace System.Xml.Serialization
{
	/// <summary>Indicates to the <see cref="T:System.Xml.Serialization.XmlSerializer" /> that the member must be treated as XML text when the class that contains it is serialized or deserialized.</summary>
	// Token: 0x0200020B RID: 523
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlTextAttribute : Attribute
	{
		/// <summary>Gets or sets the XML Schema definition language (XSD) data type of the text generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema (XSD) data type, as defined by the World Wide Web Consortium (www.w3.org) document "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the .NET data type. </exception>
		/// <exception cref="T:System.InvalidOperationException">The XML Schema data type you have specified is invalid for the property and cannot be converted to the member type. </exception>
		// Token: 0x17000361 RID: 865
		// (get) Token: 0x06001152 RID: 4434 RVA: 0x0006D730 File Offset: 0x0006B930
		public string DataType
		{
			get
			{
				if (this.dataType == null)
				{
					return string.Empty;
				}
				return this.dataType;
			}
		}

		/// <summary>Gets or sets the type of the member.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x17000362 RID: 866
		// (get) Token: 0x06001153 RID: 4435 RVA: 0x0006D746 File Offset: 0x0006B946
		public Type Type
		{
			get
			{
				return this.type;
			}
		}

		// Token: 0x06001154 RID: 4436 RVA: 0x0006D74E File Offset: 0x0006B94E
		internal void AddKeyHash(StringBuilder sb)
		{
			sb.Append("XTXA ");
			KeyHelper.AddField(sb, 1, this.type);
			KeyHelper.AddField(sb, 2, this.dataType);
			sb.Append('|');
		}

		// Token: 0x04000BE8 RID: 3048
		private string dataType;

		// Token: 0x04000BE9 RID: 3049
		private Type type;
	}
}
