name = "animefy-v2"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Build configuration for Cloudflare Pages
# Build command: npx @cloudflare/next-on-pages@1
# Build output: .vercel/output/static

[[kv_namespaces]]
binding = "KV_BINDING"
id = "430df556554942d99d22041f101e1f67"
