using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using Android.Runtime;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: NamespaceMapping(Java = "kotlin", Managed = "Kotlin")]
[assembly: NamespaceMapping(Java = "kotlin.annotation", Managed = "Kotlin.Annotation")]
[assembly: NamespaceMapping(Java = "kotlin.collections", Managed = "Kotlin.Collections")]
[assembly: NamespaceMapping(Java = "kotlin.collections.builders", Managed = "Kotlin.Collections.Builders")]
[assembly: NamespaceMapping(Java = "kotlin.collections.jdk8", Managed = "Kotlin.Collections.Jdk8")]
[assembly: NamespaceMapping(Java = "kotlin.collections.unsigned", Managed = "Kotlin.Collections.Unsigned")]
[assembly: NamespaceMapping(Java = "kotlin.comparisons", Managed = "Kotlin.Comparisons")]
[assembly: NamespaceMapping(Java = "kotlin.concurrent", Managed = "Kotlin.Concurrent")]
[assembly: NamespaceMapping(Java = "kotlin.contracts", Managed = "Kotlin.Contracts")]
[assembly: NamespaceMapping(Java = "kotlin.coroutines", Managed = "Kotlin.Coroutines")]
[assembly: NamespaceMapping(Java = "kotlin.coroutines.cancellation", Managed = "Kotlin.Coroutines.Cancellation")]
[assembly: NamespaceMapping(Java = "kotlin.coroutines.intrinsics", Managed = "Kotlin.Coroutines.Intrinsics")]
[assembly: NamespaceMapping(Java = "kotlin.coroutines.jvm.internal", Managed = "Kotlin.Coroutines.Jvm.Internal")]
[assembly: NamespaceMapping(Java = "kotlin.enums", Managed = "Kotlin.Enums")]
[assembly: NamespaceMapping(Java = "kotlin.experimental", Managed = "Kotlin.Experimental")]
[assembly: NamespaceMapping(Java = "kotlin.internal", Managed = "Kotlin.Internal")]
[assembly: NamespaceMapping(Java = "kotlin.io", Managed = "Kotlin.IO")]
[assembly: NamespaceMapping(Java = "kotlin.io.encoding", Managed = "Kotlin.IO.Encoding")]
[assembly: NamespaceMapping(Java = "kotlin.io.path", Managed = "Kotlin.IO.Path")]
[assembly: NamespaceMapping(Java = "kotlin.jdk7", Managed = "Kotlin.Jdk7")]
[assembly: NamespaceMapping(Java = "kotlin.js", Managed = "Kotlin.JS")]
[assembly: NamespaceMapping(Java = "kotlin.jvm", Managed = "Kotlin.Jvm")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.functions", Managed = "Kotlin.Jvm.Functions")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.internal", Managed = "Kotlin.Jvm.Internal")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.internal.markers", Managed = "Kotlin.Jvm.Internal.Markers")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.internal.unsafe", Managed = "Kotlin.Jvm.Internal.Unsafe")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.jdk8", Managed = "Kotlin.Jvm.Jdk8")]
[assembly: NamespaceMapping(Java = "kotlin.jvm.optionals", Managed = "Kotlin.Jvm.Optionals")]
[assembly: NamespaceMapping(Java = "kotlin.math", Managed = "Kotlin.Math")]
[assembly: NamespaceMapping(Java = "kotlin.properties", Managed = "Kotlin.Properties")]
[assembly: NamespaceMapping(Java = "kotlin.random", Managed = "Kotlin.Random")]
[assembly: NamespaceMapping(Java = "kotlin.ranges", Managed = "Kotlin.Ranges")]
[assembly: NamespaceMapping(Java = "kotlin.reflect", Managed = "Kotlin.Reflect")]
[assembly: NamespaceMapping(Java = "kotlin.sequences", Managed = "Kotlin.Sequences")]
[assembly: NamespaceMapping(Java = "kotlin.streams.jdk8", Managed = "Kotlin.Streams.Jdk8")]
[assembly: NamespaceMapping(Java = "kotlin.system", Managed = "Kotlin.System")]
[assembly: NamespaceMapping(Java = "kotlin.text", Managed = "Kotlin.Text")]
[assembly: NamespaceMapping(Java = "kotlin.text.jdk8", Managed = "Kotlin.Text.Jdk8")]
[assembly: NamespaceMapping(Java = "kotlin.time", Managed = "Kotlin.Time")]
[assembly: NamespaceMapping(Java = "kotlin.time.jdk8", Managed = "Kotlin.Time.Jdk8")]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription(".NET for Android (formerly Xamarin.Android) binding for Kotlin Standard Library")]
[assembly: AssemblyFileVersion("1.9.10")]
[assembly: AssemblyInformationalVersion("1.9.10.1")]
[assembly: AssemblyProduct("Xamarin.Kotlin.StdLib")]
[assembly: AssemblyTitle("Xamarin.Kotlin.StdLib")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/xamarin/AndroidX.git")]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
[module: RefSafetyRules(11)]
