using System;
using System.Text;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Specifies that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize the class member as an XML attribute.</summary>
	// Token: 0x020001E1 RID: 481
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue)]
	public class XmlAttributeAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlAttributeAttribute" /> class and specifies the name of the generated XML attribute.</summary>
		/// <param name="attributeName">The name of the XML attribute that the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates. </param>
		// Token: 0x06000FEE RID: 4078 RVA: 0x00064AB5 File Offset: 0x00062CB5
		public XmlAttributeAttribute(string attributeName)
		{
			this.attributeName = attributeName;
		}

		/// <summary>Gets or sets the name of the XML attribute.</summary>
		/// <returns>The name of the XML attribute. The default is the member name.</returns>
		// Token: 0x1700031E RID: 798
		// (get) Token: 0x06000FEF RID: 4079 RVA: 0x00064AC4 File Offset: 0x00062CC4
		public string AttributeName
		{
			get
			{
				if (this.attributeName == null)
				{
					return string.Empty;
				}
				return this.attributeName;
			}
		}

		/// <summary>Gets or sets the XSD data type of the XML attribute generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XSD (XML Schema Document) data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema: DataTypes".</returns>
		// Token: 0x1700031F RID: 799
		// (get) Token: 0x06000FF0 RID: 4080 RVA: 0x00064ADA File Offset: 0x00062CDA
		// (set) Token: 0x06000FF1 RID: 4081 RVA: 0x00064AF0 File Offset: 0x00062CF0
		public string DataType
		{
			get
			{
				if (this.dataType == null)
				{
					return string.Empty;
				}
				return this.dataType;
			}
			set
			{
				this.dataType = value;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the XML attribute name generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" /> is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is <see langword="XmlForm.None" />.</returns>
		// Token: 0x17000320 RID: 800
		// (get) Token: 0x06000FF2 RID: 4082 RVA: 0x00064AF9 File Offset: 0x00062CF9
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
		}

		/// <summary>Gets or sets the XML namespace of the XML attribute.</summary>
		/// <returns>The XML namespace of the XML attribute.</returns>
		// Token: 0x17000321 RID: 801
		// (get) Token: 0x06000FF3 RID: 4083 RVA: 0x00064B01 File Offset: 0x00062D01
		public string Namespace
		{
			get
			{
				return this.ns;
			}
		}

		// Token: 0x06000FF4 RID: 4084 RVA: 0x00064B0C File Offset: 0x00062D0C
		internal void AddKeyHash(StringBuilder sb)
		{
			sb.Append("XAA ");
			KeyHelper.AddField(sb, 1, this.ns);
			KeyHelper.AddField(sb, 2, this.attributeName);
			KeyHelper.AddField(sb, 3, this.form.ToString(), XmlSchemaForm.None.ToString());
			KeyHelper.AddField(sb, 4, this.dataType);
			KeyHelper.AddField(sb, 5, this.type);
			sb.Append('|');
		}

		// Token: 0x04000B56 RID: 2902
		private string attributeName;

		// Token: 0x04000B57 RID: 2903
		private string dataType;

		// Token: 0x04000B58 RID: 2904
		private Type type;

		// Token: 0x04000B59 RID: 2905
		private XmlSchemaForm form;

		// Token: 0x04000B5A RID: 2906
		private string ns;
	}
}
