using System;
using System.Text;
using System.Xml.Schema;

namespace System.Xml.Serialization
{
	/// <summary>Indicates that a public field or property represents an XML element when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes or deserializes the object that contains it.</summary>
	// Token: 0x020001E6 RID: 486
	[AttributeUsage(AttributeTargets.Property | AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.ReturnValue, AllowMultiple = true)]
	public class XmlElementAttribute : Attribute
	{
		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> class and specifies the name of the XML element.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		// Token: 0x06001014 RID: 4116 RVA: 0x00065BB8 File Offset: 0x00063DB8
		public XmlElementAttribute(string elementName)
		{
			this.elementName = elementName;
		}

		/// <summary>Initializes a new instance of the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> and specifies the name of the XML element and a derived type for the member to which the <see cref="T:System.Xml.Serialization.XmlElementAttribute" /> is applied. This member type is used when the <see cref="T:System.Xml.Serialization.XmlSerializer" /> serializes the object that contains it.</summary>
		/// <param name="elementName">The XML element name of the serialized member. </param>
		/// <param name="type">The <see cref="T:System.Type" /> of an object derived from the member's type. </param>
		// Token: 0x06001015 RID: 4117 RVA: 0x00065BCE File Offset: 0x00063DCE
		public XmlElementAttribute(string elementName, Type type)
		{
			this.elementName = elementName;
			this.type = type;
		}

		/// <summary>Gets or sets the XML Schema definition (XSD) data type of the XML element generated by the <see cref="T:System.Xml.Serialization.XmlSerializer" />.</summary>
		/// <returns>An XML Schema data type, as defined by the World Wide Web Consortium (www.w3.org) document named "XML Schema Part 2: Datatypes".</returns>
		/// <exception cref="T:System.Exception">The XML Schema data type you have specified cannot be mapped to the.NET data type. </exception>
		// Token: 0x17000334 RID: 820
		// (get) Token: 0x06001016 RID: 4118 RVA: 0x00065BEB File Offset: 0x00063DEB
		public string DataType
		{
			get
			{
				if (this.dataType == null)
				{
					return string.Empty;
				}
				return this.dataType;
			}
		}

		/// <summary>Gets or sets the name of the generated XML element.</summary>
		/// <returns>The name of the generated XML element. The default is the member identifier.</returns>
		// Token: 0x17000335 RID: 821
		// (get) Token: 0x06001017 RID: 4119 RVA: 0x00065C01 File Offset: 0x00063E01
		public string ElementName
		{
			get
			{
				if (this.elementName == null)
				{
					return string.Empty;
				}
				return this.elementName;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the element is qualified.</summary>
		/// <returns>One of the <see cref="T:System.Xml.Schema.XmlSchemaForm" /> values. The default is <see cref="F:System.Xml.Schema.XmlSchemaForm.None" />.</returns>
		// Token: 0x17000336 RID: 822
		// (get) Token: 0x06001018 RID: 4120 RVA: 0x00065C17 File Offset: 0x00063E17
		public XmlSchemaForm Form
		{
			get
			{
				return this.form;
			}
		}

		/// <summary>Gets or sets the namespace assigned to the XML element that results when the class is serialized.</summary>
		/// <returns>The namespace of the XML element.</returns>
		// Token: 0x17000337 RID: 823
		// (get) Token: 0x06001019 RID: 4121 RVA: 0x00065C1F File Offset: 0x00063E1F
		public string Namespace
		{
			get
			{
				return this.ns;
			}
		}

		/// <summary>Gets or sets a value that indicates whether the <see cref="T:System.Xml.Serialization.XmlSerializer" /> must serialize a member that is set to <see langword="null" /> as an empty tag with the <see langword="xsi:nil" /> attribute set to <see langword="true" />.</summary>
		/// <returns>
		///     <see langword="true" /> if the <see cref="T:System.Xml.Serialization.XmlSerializer" /> generates the <see langword="xsi:nil" /> attribute; otherwise, <see langword="false" />.</returns>
		// Token: 0x17000338 RID: 824
		// (get) Token: 0x0600101A RID: 4122 RVA: 0x00065C27 File Offset: 0x00063E27
		public bool IsNullable
		{
			get
			{
				return this.isNullable;
			}
		}

		/// <summary>Gets or sets the explicit order in which the elements are serialized or deserialized.</summary>
		/// <returns>The order of the code generation.</returns>
		// Token: 0x17000339 RID: 825
		// (get) Token: 0x0600101B RID: 4123 RVA: 0x00065C2F File Offset: 0x00063E2F
		public int Order
		{
			get
			{
				return this.order;
			}
		}

		/// <summary>Gets or sets the object type used to represent the XML element.</summary>
		/// <returns>The <see cref="T:System.Type" /> of the member.</returns>
		// Token: 0x1700033A RID: 826
		// (get) Token: 0x0600101C RID: 4124 RVA: 0x00065C37 File Offset: 0x00063E37
		public Type Type
		{
			get
			{
				return this.type;
			}
		}

		// Token: 0x0600101D RID: 4125 RVA: 0x00065C40 File Offset: 0x00063E40
		internal void AddKeyHash(StringBuilder sb)
		{
			sb.Append("XEA ");
			KeyHelper.AddField(sb, 1, this.ns);
			KeyHelper.AddField(sb, 2, this.elementName);
			KeyHelper.AddField(sb, 3, this.form.ToString(), XmlSchemaForm.None.ToString());
			KeyHelper.AddField(sb, 4, this.dataType);
			KeyHelper.AddField(sb, 5, this.type);
			KeyHelper.AddField(sb, 6, this.isNullable);
			sb.Append('|');
		}

		// Token: 0x04000B6C RID: 2924
		private string dataType;

		// Token: 0x04000B6D RID: 2925
		private string elementName;

		// Token: 0x04000B6E RID: 2926
		private XmlSchemaForm form;

		// Token: 0x04000B6F RID: 2927
		private string ns;

		// Token: 0x04000B70 RID: 2928
		private bool isNullable;

		// Token: 0x04000B71 RID: 2929
		private Type type;

		// Token: 0x04000B72 RID: 2930
		private int order = -1;
	}
}
