using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.Versioning;
using System.Security;
using Android;
using Android.Runtime;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyMetadata("BUILD_COMMIT", "2059f2bbde9a3f07dd3e2df24b21e63c14d3a7be")]
[assembly: AssemblyMetadata("BUILD_NUMBER", "20230915.2")]
[assembly: AssemblyMetadata("BUILD_TIMESTAMP", "9/15/2023 8:19:27 AM")]
[assembly: LinkerSafe]
[assembly: AssemblyMetadata("IsTrimmable", "True")]
[assembly: NamespaceMapping(Java = "com.google.android.material.animation", Managed = "Google.Android.Material.Animation")]
[assembly: NamespaceMapping(Java = "com.google.android.material.appbar", Managed = "Google.Android.Material.AppBar")]
[assembly: NamespaceMapping(Java = "com.google.android.material.badge", Managed = "Google.Android.Material.Badge")]
[assembly: NamespaceMapping(Java = "com.google.android.material.behavior", Managed = "Google.Android.Material.Behavior")]
[assembly: NamespaceMapping(Java = "com.google.android.material.bottomappbar", Managed = "Google.Android.Material.BottomAppBar")]
[assembly: NamespaceMapping(Java = "com.google.android.material.bottomnavigation", Managed = "Google.Android.Material.BottomNavigation")]
[assembly: NamespaceMapping(Java = "com.google.android.material.bottomsheet", Managed = "Google.Android.Material.BottomSheet")]
[assembly: NamespaceMapping(Java = "com.google.android.material.button", Managed = "Google.Android.Material.Button")]
[assembly: NamespaceMapping(Java = "com.google.android.material.canvas", Managed = "Google.Android.Material.Canvas")]
[assembly: NamespaceMapping(Java = "com.google.android.material.card", Managed = "Google.Android.Material.Card")]
[assembly: NamespaceMapping(Java = "com.google.android.material.carousel", Managed = "Google.Android.Material.Carousel")]
[assembly: NamespaceMapping(Java = "com.google.android.material.checkbox", Managed = "Google.Android.Material.CheckBox")]
[assembly: NamespaceMapping(Java = "com.google.android.material.chip", Managed = "Google.Android.Material.Chip")]
[assembly: NamespaceMapping(Java = "com.google.android.material.circularreveal", Managed = "Google.Android.Material.CircularReveal")]
[assembly: NamespaceMapping(Java = "com.google.android.material.circularreveal.cardview", Managed = "Google.Android.Material.CircularReveal.CardView")]
[assembly: NamespaceMapping(Java = "com.google.android.material.circularreveal.coordinatorlayout", Managed = "Google.Android.Material.CircularReveal.CoordinatorLayout")]
[assembly: NamespaceMapping(Java = "com.google.android.material.color", Managed = "Google.Android.Material.Color")]
[assembly: NamespaceMapping(Java = "com.google.android.material.color.utilities", Managed = "Google.Android.Material.Color.Utilities")]
[assembly: NamespaceMapping(Java = "com.google.android.material.datepicker", Managed = "Google.Android.Material.DatePicker")]
[assembly: NamespaceMapping(Java = "com.google.android.material.dialog", Managed = "Google.Android.Material.Dialog")]
[assembly: NamespaceMapping(Java = "com.google.android.material.divider", Managed = "Google.Android.Material.Divider")]
[assembly: NamespaceMapping(Java = "com.google.android.material.drawable", Managed = "Google.Android.Material.Drawable")]
[assembly: NamespaceMapping(Java = "com.google.android.material.elevation", Managed = "Google.Android.Material.Elevation")]
[assembly: NamespaceMapping(Java = "com.google.android.material.expandable", Managed = "Google.Android.Material.Expandable")]
[assembly: NamespaceMapping(Java = "com.google.android.material.floatingactionbutton", Managed = "Google.Android.Material.FloatingActionButton")]
[assembly: NamespaceMapping(Java = "com.google.android.material.imageview", Managed = "Google.Android.Material.ImageView")]
[assembly: NamespaceMapping(Java = "com.google.android.material.internal", Managed = "Google.Android.Material.Internal")]
[assembly: NamespaceMapping(Java = "com.google.android.material.materialswitch", Managed = "Google.Android.Material.MaterialSwitch")]
[assembly: NamespaceMapping(Java = "com.google.android.material.math", Managed = "Google.Android.Material.Math")]
[assembly: NamespaceMapping(Java = "com.google.android.material.motion", Managed = "Google.Android.Material.Motion")]
[assembly: NamespaceMapping(Java = "com.google.android.material.navigation", Managed = "Google.Android.Material.Navigation")]
[assembly: NamespaceMapping(Java = "com.google.android.material.navigationrail", Managed = "Google.Android.Material.NavigationRail")]
[assembly: NamespaceMapping(Java = "com.google.android.material.progressindicator", Managed = "Google.Android.Material.ProgressIndicator")]
[assembly: NamespaceMapping(Java = "com.google.android.material.radiobutton", Managed = "Google.Android.Material.RadioButton")]
[assembly: NamespaceMapping(Java = "com.google.android.material.resources", Managed = "Google.Android.Material.Resources")]
[assembly: NamespaceMapping(Java = "com.google.android.material.ripple", Managed = "Google.Android.Material.Ripple")]
[assembly: NamespaceMapping(Java = "com.google.android.material.search", Managed = "Google.Android.Material.Search")]
[assembly: NamespaceMapping(Java = "com.google.android.material.shadow", Managed = "Google.Android.Material.Shadow")]
[assembly: NamespaceMapping(Java = "com.google.android.material.shape", Managed = "Google.Android.Material.Shape")]
[assembly: NamespaceMapping(Java = "com.google.android.material.sidesheet", Managed = "Google.Android.Material.SideSheet")]
[assembly: NamespaceMapping(Java = "com.google.android.material.slider", Managed = "Google.Android.Material.Slider")]
[assembly: NamespaceMapping(Java = "com.google.android.material.snackbar", Managed = "Google.Android.Material.Snackbar")]
[assembly: NamespaceMapping(Java = "com.google.android.material.stateful", Managed = "Google.Android.Material.Stateful")]
[assembly: NamespaceMapping(Java = "com.google.android.material.switchmaterial", Managed = "Google.Android.Material.SwitchMaterial")]
[assembly: NamespaceMapping(Java = "com.google.android.material.tabs", Managed = "Google.Android.Material.Tabs")]
[assembly: NamespaceMapping(Java = "com.google.android.material.textfield", Managed = "Google.Android.Material.TextField")]
[assembly: NamespaceMapping(Java = "com.google.android.material.textview", Managed = "Google.Android.Material.TextView")]
[assembly: NamespaceMapping(Java = "com.google.android.material.theme", Managed = "Google.Android.Material.Theme")]
[assembly: NamespaceMapping(Java = "com.google.android.material.theme.overlay", Managed = "Google.Android.Material.Theme.Overlay")]
[assembly: NamespaceMapping(Java = "com.google.android.material.timepicker", Managed = "Google.Android.Material.TimePicker")]
[assembly: NamespaceMapping(Java = "com.google.android.material.tooltip", Managed = "Google.Android.Material.Tooltip")]
[assembly: NamespaceMapping(Java = "com.google.android.material.transformation", Managed = "Google.Android.Material.Transformation")]
[assembly: NamespaceMapping(Java = "com.google.android.material.transition", Managed = "Google.Android.Material.Transition")]
[assembly: NamespaceMapping(Java = "com.google.android.material.transition.platform", Managed = "Google.Android.Material.Transition.Platform")]
[assembly: AssemblyCompany("Microsoft")]
[assembly: AssemblyConfiguration("Release")]
[assembly: AssemblyCopyright("© Microsoft Corporation. All rights reserved.")]
[assembly: AssemblyDescription(".NET for Android (formerly Xamarin.Android) bindings for AndroidX library 'com.google.android.material:material'.")]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: AssemblyInformationalVersion("1.0.0")]
[assembly: AssemblyProduct("Xamarin.Google.Android.Material")]
[assembly: AssemblyTitle("Xamarin.Google.Android.Material")]
[assembly: AssemblyMetadata("RepositoryUrl", "https://github.com/xamarin/AndroidX.git")]
[module: RefSafetyRules(11)]
