using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using System.Runtime.Versioning;
using System.Security;
using System.Security.Permissions;
using Android.Runtime;

[assembly: AssemblyVersion("1.0.0.0")]
[assembly: AssemblyTitle("UnityAds")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("UnityAds")]
[assembly: AssemblyCopyright("Copyright ©  2018")]
[assembly: AssemblyTrademark("")]
[assembly: ComVisible(false)]
[assembly: AssemblyFileVersion("1.0.0.0")]
[assembly: NamespaceMapping(Java = "com.unity3d.ads", Managed = "Com.Unity3d.Ads")]
[assembly: NamespaceMapping(Java = "com.unity3d.ads.metadata", Managed = "Com.Unity3d.Ads.Metadata")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.common", Managed = "Com.Unity3d.Scar.Adapter.Common")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.common.requests", Managed = "Com.Unity3d.Scar.Adapter.Common.Requests")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.common.scarads", Managed = "Com.Unity3d.Scar.Adapter.Common.Scarads")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.common.signals", Managed = "Com.Unity3d.Scar.Adapter.Common.Signals")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1920", Managed = "Com.Unity3d.Scar.Adapter.V1920")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1920.scarads", Managed = "Com.Unity3d.Scar.Adapter.V1920.Scarads")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1920.signals", Managed = "Com.Unity3d.Scar.Adapter.V1920.Signals")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1950", Managed = "Com.Unity3d.Scar.Adapter.V1950")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1950.scarads", Managed = "Com.Unity3d.Scar.Adapter.V1950.Scarads")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v1950.signals", Managed = "Com.Unity3d.Scar.Adapter.V1950.Signals")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2000", Managed = "Com.Unity3d.Scar.Adapter.V2000")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2000.scarads", Managed = "Com.Unity3d.Scar.Adapter.V2000.Scarads")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2000.signals", Managed = "Com.Unity3d.Scar.Adapter.V2000.Signals")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2100", Managed = "Com.Unity3d.Scar.Adapter.V2100")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2100.requests", Managed = "Com.Unity3d.Scar.Adapter.V2100.Requests")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2100.scarads", Managed = "Com.Unity3d.Scar.Adapter.V2100.Scarads")]
[assembly: NamespaceMapping(Java = "com.unity3d.scar.adapter.v2100.signals", Managed = "Com.Unity3d.Scar.Adapter.V2100.Signals")]
[assembly: NamespaceMapping(Java = "com.unity3d.services", Managed = "Com.Unity3d.Services")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads", Managed = "Com.Unity3d.Services.Ads")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.adunit", Managed = "Com.Unity3d.Services.Ads.Adunit")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.api", Managed = "Com.Unity3d.Services.Ads.Api")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.configuration", Managed = "Com.Unity3d.Services.Ads.Configuration")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar", Managed = "Com.Unity3d.Services.Ads.Gmascar")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.adapters", Managed = "Com.Unity3d.Services.Ads.Gmascar.Adapters")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.bridges", Managed = "Com.Unity3d.Services.Ads.Gmascar.Bridges")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.bridges.mobileads", Managed = "Com.Unity3d.Services.Ads.Gmascar.Bridges.Mobileads")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.finder", Managed = "Com.Unity3d.Services.Ads.Gmascar.Finder")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.handlers", Managed = "Com.Unity3d.Services.Ads.Gmascar.Handlers")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.listeners", Managed = "Com.Unity3d.Services.Ads.Gmascar.Listeners")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.gmascar.utils", Managed = "Com.Unity3d.Services.Ads.Gmascar.Utils")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.operation", Managed = "Com.Unity3d.Services.Ads.Operation")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.operation.load", Managed = "Com.Unity3d.Services.Ads.Operation.Load")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.operation.show", Managed = "Com.Unity3d.Services.Ads.Operation.Show")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.token", Managed = "Com.Unity3d.Services.Ads.Token")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.video", Managed = "Com.Unity3d.Services.Ads.Video")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.ads.webplayer", Managed = "Com.Unity3d.Services.Ads.Webplayer")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.analytics", Managed = "Com.Unity3d.Services.Analytics")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.analytics.core.api", Managed = "Com.Unity3d.Services.Analytics.Core.Api")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.analytics.core.configuration", Managed = "Com.Unity3d.Services.Analytics.Core.Configuration")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.analytics.interfaces", Managed = "Com.Unity3d.Services.Analytics.Interfaces")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners", Managed = "Com.Unity3d.Services.Banners")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners.api", Managed = "Com.Unity3d.Services.Banners.Api")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners.bridge", Managed = "Com.Unity3d.Services.Banners.Bridge")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners.configuration", Managed = "Com.Unity3d.Services.Banners.Configuration")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners.properties", Managed = "Com.Unity3d.Services.Banners.Properties")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.banners.view", Managed = "Com.Unity3d.Services.Banners.View")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.api", Managed = "Com.Unity3d.Services.Core.Api")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.broadcast", Managed = "Com.Unity3d.Services.Core.Broadcast")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.cache", Managed = "Com.Unity3d.Services.Core.Cache")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.configuration", Managed = "Com.Unity3d.Services.Core.Configuration")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.connectivity", Managed = "Com.Unity3d.Services.Core.Connectivity")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.device", Managed = "Com.Unity3d.Services.Core.Device")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.device.reader", Managed = "Com.Unity3d.Services.Core.Device.Reader")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.device.reader.pii", Managed = "Com.Unity3d.Services.Core.Device.Reader.Pii")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.di", Managed = "Com.Unity3d.Services.Core.DI")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.domain", Managed = "Com.Unity3d.Services.Core.Domain")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.domain.task", Managed = "Com.Unity3d.Services.Core.Domain.Task")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.extensions", Managed = "Com.Unity3d.Services.Core.Extensions")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.lifecycle", Managed = "Com.Unity3d.Services.Core.Lifecycle")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.log", Managed = "Com.Unity3d.Services.Core.Log")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.misc", Managed = "Com.Unity3d.Services.Core.Misc")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.preferences", Managed = "Com.Unity3d.Services.Core.Preferences")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.properties", Managed = "Com.Unity3d.Services.Core.Properties")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.reflection", Managed = "Com.Unity3d.Services.Core.Reflection")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.request", Managed = "Com.Unity3d.Services.Core.Request")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.request.metrics", Managed = "Com.Unity3d.Services.Core.Request.Metrics")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.sensorinfo", Managed = "Com.Unity3d.Services.Core.Sensorinfo")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.timer", Managed = "Com.Unity3d.Services.Core.Timer")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.webview", Managed = "Com.Unity3d.Services.Core.Webview")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.webview.bridge", Managed = "Com.Unity3d.Services.Core.Webview.Bridge")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.core.webview.bridge.invocation", Managed = "Com.Unity3d.Services.Core.Webview.Bridge.Invocation")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store", Managed = "Com.Unity3d.Services.Store")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.core", Managed = "Com.Unity3d.Services.Store.Core")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.core.api", Managed = "Com.Unity3d.Services.Store.Core.Api")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.core.configuration", Managed = "Com.Unity3d.Services.Store.Core.Configuration")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl", Managed = "Com.Unity3d.Services.Store.Gpbl")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.bridges", Managed = "Com.Unity3d.Services.Store.Gpbl.Bridges")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.bridges.billingclient", Managed = "Com.Unity3d.Services.Store.Gpbl.Bridges.Billingclient")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.bridges.billingclient.common", Managed = "Com.Unity3d.Services.Store.Gpbl.Bridges.Billingclient.Common")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.bridges.billingclient.v3", Managed = "Com.Unity3d.Services.Store.Gpbl.Bridges.Billingclient.V3")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.bridges.billingclient.v4", Managed = "Com.Unity3d.Services.Store.Gpbl.Bridges.Billingclient.V4")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.gpbl.proxies", Managed = "Com.Unity3d.Services.Store.Gpbl.Proxies")]
[assembly: NamespaceMapping(Java = "com.unity3d.services.store.listeners", Managed = "Com.Unity3d.Services.Store.Listeners")]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
