using System;

namespace System
{
	/// <summary>Represents the method that will handle an event when the event provides data. </summary>
	/// <param name="sender">The source of the event.</param>
	/// <param name="e">An object that contains the event data. </param>
	/// <typeparam name="TEventArgs">The type of the event data generated by the event.</typeparam>
	// Token: 0x0200009A RID: 154
	// (Invoke) Token: 0x0600053C RID: 1340
	public delegate void EventHandler<TEventArgs>(object sender, TEventArgs e);
}
